### ISSUE TITLE
Get error message when I install

### ISSUE THREAD

**Issue by zhouhao27** [nikhil-thakkar/react-native-patch#4] opened 2018-12-18 02:53 UTC
```
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/react-native-patch/src/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

```

**Comment by nikhil-thakkar** [comment] 2018-12-18 06:52
@zhouhao27 Here are couple of questions:
1. Did you install the package globally?
2. What version of npm you are using?
3. Did you install the latest version of the this package wiz. 0.2.0?

**Comment by zhouhao27** [comment] 2018-12-18 07:48
Yes. I tried to install it globally.

The npm version is 6.5.

I didn't try wiz. 0.2.0.

**Comment by nikhil-thakkar** [comment] 2018-12-18 13:42
@zhouhao27 the solution works but the problem is you have run that command every time you want do some development.
This module helps in resolving the issue with a permanent solution.
Of source you can add the command "react-native run-ios --port 9999" to package.json under scripts tag. And then instead of running "react-native run-ios --port 9999" you will run "npm run start" where start being the key in the scripts tag.

In order to have a resolution for this opened issue, can you please let me know on which machine you are running the install script. Is it Linux or Mac?

FYI: This package is only tested on Mac.

**Comment by nikhil-thakkar** [comment] 2019-01-27 04:45
Closing this issue due to inactivity.

**Closed by nikhil-thakkar** 2019-01-27 04:45 UTC
